export const DATACUBE_DIMENSION = 'DATACUBE_DIMENSION';
export const DATACUBE_OBS = 'DATACUBE_DIMENSION';

export const SETTINGS_CONTEXT = 'SETTINGS_CONTEXT';

export const CONTEXT_SOFTWAREENGINEERING = 'CONTEXT_SOFTWAREENGINEERING';
export const CONTEXT_PERSON = 'CONTEXT_PERSON';
